{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.namespace }}
data:
{{ toYaml $.Values.configmap.data | indent 2 }}
{{- end }}
