name: Docker Image CI

on:
  push:
    branches:
     - main
     - release/*
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Build image and push to Github Container Repo
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ github.run_number }}
        push: ${{ github.ref == 'refs/heads/main' }}
    - name: Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
