name: Docker Image CI

on:
  push:
    branches:
     - main
     - release/*
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: push-docker-image-using-github-actions
    - name: Build and push to GHCR
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        tags: ${{ github.run_number }}
        push: ${{ github.ref == 'refs/heads/main' }}
    - name: Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
