name: Create and publish a Docker image

on:
  push:
    branches: ['release/**', 'main']
  pull_request:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_IMAGE_TAG: ${{ github.ref_name }}-rc${{ github.run_number }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Printing env variables
        run: env | sort
        
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{ secrets.GHCR_PAT }}
          event-type: "complete-workflow"
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
        
        
     
          
     
