name: Trigger the pipeline just after first workflow

on:
  workflow_dispatch:
     inputs:
      value:
        description: "Type Yes or No"
        options:
          - "Yes"
          - "No"
        required: true
  workflow_run:
    workflows: ["Create and publish a Docker image"]
    types:
      - completed
        
      
      
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Triggered the worflow
      run: echo "Triggered the worflow"
    - name: Printing value from another workflow
      run: echo "${{ github.event.client_payload.test_sha }}"
    
